//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RegistroEntities : DbContext
    {
        public RegistroEntities()
            : base("name=RegistroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<test_Habilidad> test_Habilidad { get; set; }
        public virtual DbSet<test_Telefono> test_Telefono { get; set; }
        public virtual DbSet<test_Usuario> test_Usuario { get; set; }
    
        public virtual ObjectResult<test_Habilidad> test_Habilidad_Read()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Habilidad_Read");
        }
    
        public virtual ObjectResult<test_Habilidad> test_Habilidad_Read(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Habilidad_Read", mergeOption);
        }
    
        public virtual ObjectResult<test_Habilidad> test_Habilidad_ReadById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Habilidad_ReadById", idParameter);
        }
    
        public virtual ObjectResult<test_Habilidad> test_Habilidad_ReadById(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Habilidad_ReadById", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_PhoneCreate(string usuarioCedula, string telefono)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_PhoneCreate", usuarioCedulaParameter, telefonoParameter);
        }
    
        public virtual ObjectResult<test_Telefono> test_PhoneReadByUserId(string usuarioCedula)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Telefono>("test_PhoneReadByUserId", usuarioCedulaParameter);
        }
    
        public virtual ObjectResult<test_Telefono> test_PhoneReadByUserId(string usuarioCedula, MergeOption mergeOption)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Telefono>("test_PhoneReadByUserId", mergeOption, usuarioCedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_PhoneUpdate(string usuarioCedula, string telefono)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_PhoneUpdate", usuarioCedulaParameter, telefonoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_UserCreate(string cedula, string nombre, string usuario, string clave, string correo, Nullable<int> tipoDeUsuario, Nullable<int> tipoDeIdentificacion)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var tipoDeUsuarioParameter = tipoDeUsuario.HasValue ?
                new ObjectParameter("TipoDeUsuario", tipoDeUsuario) :
                new ObjectParameter("TipoDeUsuario", typeof(int));
    
            var tipoDeIdentificacionParameter = tipoDeIdentificacion.HasValue ?
                new ObjectParameter("TipoDeIdentificacion", tipoDeIdentificacion) :
                new ObjectParameter("TipoDeIdentificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_UserCreate", cedulaParameter, nombreParameter, usuarioParameter, claveParameter, correoParameter, tipoDeUsuarioParameter, tipoDeIdentificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_UserDelete(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_UserDelete", cedulaParameter);
        }
    
        public virtual ObjectResult<test_Usuario> test_UserRead()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Usuario>("test_UserRead");
        }
    
        public virtual ObjectResult<test_Usuario> test_UserRead(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Usuario>("test_UserRead", mergeOption);
        }
    
        public virtual ObjectResult<test_Usuario> test_UserReadById(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Usuario>("test_UserReadById", cedulaParameter);
        }
    
        public virtual ObjectResult<test_Usuario> test_UserReadById(string cedula, MergeOption mergeOption)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Usuario>("test_UserReadById", mergeOption, cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_UserUpdate(string cedula, string nombre, string usuario, string clave, string correo, Nullable<int> tipoDeUsuario, Nullable<int> tipoDeIdentificacion)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var tipoDeUsuarioParameter = tipoDeUsuario.HasValue ?
                new ObjectParameter("TipoDeUsuario", tipoDeUsuario) :
                new ObjectParameter("TipoDeUsuario", typeof(int));
    
            var tipoDeIdentificacionParameter = tipoDeIdentificacion.HasValue ?
                new ObjectParameter("TipoDeIdentificacion", tipoDeIdentificacion) :
                new ObjectParameter("TipoDeIdentificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_UserUpdate", cedulaParameter, nombreParameter, usuarioParameter, claveParameter, correoParameter, tipoDeUsuarioParameter, tipoDeIdentificacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> test_Usuario_Habilidad_Create(string usuarioCedula, Nullable<int> idHabilidad)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            var idHabilidadParameter = idHabilidad.HasValue ?
                new ObjectParameter("IdHabilidad", idHabilidad) :
                new ObjectParameter("IdHabilidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("test_Usuario_Habilidad_Create", usuarioCedulaParameter, idHabilidadParameter);
        }
    
        public virtual ObjectResult<test_Usuario_Habilidad_ReadByUserId_Result> test_Usuario_Habilidad_ReadByUserId(string usuarioCedula)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Usuario_Habilidad_ReadByUserId_Result>("test_Usuario_Habilidad_ReadByUserId", usuarioCedulaParameter);
        }
    
        public virtual ObjectResult<test_Habilidad> test_Usuario_Habilidad_Update(string usuarioCedula, Nullable<int> idHabilidad)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            var idHabilidadParameter = idHabilidad.HasValue ?
                new ObjectParameter("IdHabilidad", idHabilidad) :
                new ObjectParameter("IdHabilidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Usuario_Habilidad_Update", usuarioCedulaParameter, idHabilidadParameter);
        }
    
        public virtual ObjectResult<test_Habilidad> test_Usuario_Habilidad_Update(string usuarioCedula, Nullable<int> idHabilidad, MergeOption mergeOption)
        {
            var usuarioCedulaParameter = usuarioCedula != null ?
                new ObjectParameter("UsuarioCedula", usuarioCedula) :
                new ObjectParameter("UsuarioCedula", typeof(string));
    
            var idHabilidadParameter = idHabilidad.HasValue ?
                new ObjectParameter("IdHabilidad", idHabilidad) :
                new ObjectParameter("IdHabilidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Habilidad>("test_Usuario_Habilidad_Update", mergeOption, usuarioCedulaParameter, idHabilidadParameter);
        }
    
        public virtual ObjectResult<test_Telefono> test_PhoneReadByTelefono(string telefono)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Telefono>("test_PhoneReadByTelefono", telefonoParameter);
        }
    
        public virtual ObjectResult<test_Telefono> test_PhoneReadByTelefono(string telefono, MergeOption mergeOption)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test_Telefono>("test_PhoneReadByTelefono", mergeOption, telefonoParameter);
        }
    }
}
